### ISSUE TITLE
Publish current master to NPM

### ISSUE THREAD

**Issue by arbue** [andywer/typed-emitter#18]
Hi,
would it be possible to release the current master of the package to npmjs. The merged fix in #16 is required for the build of packages with the pkg tool.

Thanks in advance!

**Comment by andywer** [comment]
Hey @arbue. Sure, how urgent is it? And sorry for the inconvenience.

Will probably publish tomorrow morning (~12 hours from now).

**Comment by andywer** [comment]
@arbue Just published latest `master` as v1.4.0 😉
