### ISSUE TITLE
Type 'MessageEvents' does not satisfy the constraint 'EventMap'.

### ISSUE THREAD

**Issue by grunklejp** [andywer/typed-emitter#26]
Index signature for type 'string' is missing in type 'MessageEvents'.

Works if you switch EventMessage to a type instead of an interface.

[ Example playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogbhAdsAsgQzFAvFA3gKCigG0BrCEALigGdgAnAS0QHMBdagCgDpe16WNamkQhibAJTYAfFDgB7RgBN8AX3z4A9ACpthbVAAq4CAFoaaAGbQICZFAgBbRsGAR63ffqgBVGtBcoABtGcihgAAtGIS8oAwADRNBIGgBjJjBgb2Y3eks0VOgUEHgkYBo8byJ3enl6Lhq66hh6WvopLFkFZQBuKqhHCBoLFgguS1rHajomVgAaKFT5ZDLphmYWDq7FJT64qHU47yXEOgGS51d3bChECAB3WDtgGEvczik0CuNIJVeXXIAHmKpWQNGkez0+0cFwB7m4ThcnAARI16MiFsiAB7IqRQTSaKCA0xQADqjCCQUWaGAqQi4SiFWSNladUhUES8X0mnwOXc+UKRhMf2e-yu9EBoPKDixbkQSgqUvQYFkBCIaCUSgAMtE5e5JTK5QqoOQQPJLE8yuCoJxbKtYAsQnQkO5ms8aMQYJJqJFooQoMsDRBZUhjabzZawbJbc9mo7dS76pHyp7vQy-URloUgyH5RVwxapdaY-aYPHnXck0XUxIfYz-WB6BBIPKdRX9TBDaH8xQI0Xo3bkHHggnK26rTW6xmoI3m6GAPKIQptvUSzvBo09s2F90D2MOkftqvuyfpmgaTOWSw5zcm3s7q3SEtDg9O1fjsGn33nohNxzyBAAEFKRXRMaBvbs723ZNi0HYAAH5mlrM9-T-ACIFAysILzKC+13G04OHN9Ew-FMvWQ78LwcS5sLDe8YL3UsFl4bh+EEagAAV+DQQZcnA6svWkZCACN5HkIIIBEf0CSMCJoBoIJ5DAMAQA5OCADkeKGD54igJtgAAV3oRBwhMKBonCeQBhcRgWBpaBmXMpd5EcMAaUYYSKRsoYoBJfxoAAYgAVn9DStIqD4uALGCoAAH1odZWDi2gQEcUSggkcRULQe5MPcfiuxw6L+wI-cYGQgS2CyohiMrAqN0g4r8OfYAkNIj0vWqw9VwAYXkAzkForc8MfUrS2QxADLS9wqNGVA0CxPL6AiiapuEmaiH8ebFtHfKbUcBalqEW41vcCj62k3R-X2JsAEcDMYJslCgYTVPiAAxSYpS5Ih9gAAX8qAIlcMAhAJFgXAiAzhO4JZHE0JRbBEGgIgAK00egsVRmhTAmFzTERcVNGiGgDKGTQABYApJsm4cGZBTAANkZoKAEYAAYKcZrnru0HkiAAfQFuDjqLNQNGDMA6mAKBEfyAyghln4IBFMoxVyDQNEYVzpeTdXrjxxwoFRd1kQ0GSABEIEsZhoDNIzqLhegAHImRMCoQjCSIaUoLRCQAaQoUjbi0nooAANTQIIyeoJaoEsAbUmARhlloWzEBpIyIF5FY8gKIohhGCAi0qapWSTW1y+acutjkHY5n9QZhjQUYuFEpQqAS2YWAWQ21m72vuhUdR8BOM4m6L-X6BuO5HilKePigL4hV+ee3n1FBC5b4vd3NwkAHExOewBeDcAWR38An7ep4RS4UUv0YMWNgAJRgGXcCAAEJH+RRB5FMJswBBBAH9NwdBYYuVxHvFeEAADK6RGCZCgPcCkVJUg0jpAyeQ-hrJ0DQOQCogBocgvlvUY19CZ3zQBSb+L835Ni-piX+-9mxAJAUMYA4DHCQPvsXdeHhyHIm4dQ1+kR370PCPQMmEgoGH3kCfc+3Dr7LBRGiR+lc2jVzaLXXA+IDAsTiISVQUi-bQLgRkGWyDKTUlpPSSIWDoDOFwfgqARCFG8O4Eo1E5dVFon7hsLROioB6L5gcKRrinbuMQCifIFIs7eKrrAGuMg8ABKCQYoxQA)

**Comment by andywer** [comment]
Thanks for reporting, @johnpaulkiser!

Slipped in with the new release earlier today.
