### ISSUE TITLE
Property __events introduced for FromEvent breaks EventEmitter inheritance

### ISSUE THREAD

**Issue by evanshortiss** [andywer/typed-emitter#29]
Attempting to create a class that extends EventEmitter per the README fails:. For example:

```
export class Foo extends (EventEmitter as new () => TypedEmitter<MyEvents>) {}
```

The error reported is:

```
Property '__events' is missing in type 'EventEmitter' but required in type 'TypedEventEmitter<MyEvents>'
```

This appears to happen due to [these lines to support FromEvent](https://github.com/andywer/typed-emitter/blob/master/index.d.ts#L42-L46). Removing those fixes the issue.

Casting to `unknown` first will resolve the issue, i.e ` class Foo extends EventEmitter as unknown as new () => TypedEmitter<MyEvents>` is working fine. 

Should the documentation be updated?

**Comment by andywer** [comment]
Thanks for reporting, @evanshortiss!

No, we shouldn't update the readme, this is definitely a bug we need to fix 😕
Maybe a quick fix could be to declare `__events` as an optional property.

**Comment by andywer** [comment]
@huan Thoughts?

**Comment by huan** [comment]
@andywer I have been facing the same issue and I'm using the same workaround as @evanshortiss did:

https://github.com/wechaty/wechaty/blob/6db8f6a62cad0d6e2b7e139927df3d21ebdbead9/src/schemas/wechaty-events.ts#L221-L223

I have thought about this for some time but have no better ideas yet.

**Comment by andywer** [comment]
@huan What about this?

> Maybe a quick fix could be to declare __events as an optional property.

**Comment by evanshortiss** [comment]
> Maybe a quick fix could be to declare __events as an optional property.

This works for me. I guess it might be a bit awkward for devs using `FromEvent`? Another option might be to create a separate interface for the FromEvent typing? Something like this maybe?

```
export interface TypedFromEmitter extends TypedEventEmitter { __events: Events }
```

**Comment by huan** [comment]
I think creating a separate interface might be clearer for the solution, and it will not introduce any unexpected behavior for the user who does not need this feature.
