### ISSUE TITLE
NPM Package not updated

### ISSUE THREAD

**Issue by Ed-zo** [andywer/typed-emitter#4]
Hi, I found an error with `removeAllListeners` that was already fixed in https://github.com/andywer/typed-emitter/commit/8b10c91e56998f0f987e96ff4b61a0608d9d3335. But the NPM package does not have this fix. Can you please update it ? Thank you.

**Comment by andywer** [comment]
Ohhh. How did that happen? …

Anyway, published it as v1.0.0 🚀
Thanks for pointing out!
